// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListFileListsParams creates a new ListFileListsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListFileListsParams() *ListFileListsParams {
	return &ListFileListsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListFileListsParamsWithTimeout creates a new ListFileListsParams object
// with the ability to set a timeout on a request.
func NewListFileListsParamsWithTimeout(timeout time.Duration) *ListFileListsParams {
	return &ListFileListsParams{
		timeout: timeout,
	}
}

// NewListFileListsParamsWithContext creates a new ListFileListsParams object
// with the ability to set a context for a request.
func NewListFileListsParamsWithContext(ctx context.Context) *ListFileListsParams {
	return &ListFileListsParams{
		Context: ctx,
	}
}

// NewListFileListsParamsWithHTTPClient creates a new ListFileListsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListFileListsParamsWithHTTPClient(client *http.Client) *ListFileListsParams {
	return &ListFileListsParams{
		HTTPClient: client,
	}
}

/* ListFileListsParams contains all the parameters to send to the API endpoint
   for the list file lists operation.

   Typically these are written to a http.Request.
*/
type ListFileListsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list file lists params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListFileListsParams) WithDefaults() *ListFileListsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list file lists params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListFileListsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list file lists params
func (o *ListFileListsParams) WithTimeout(timeout time.Duration) *ListFileListsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list file lists params
func (o *ListFileListsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list file lists params
func (o *ListFileListsParams) WithContext(ctx context.Context) *ListFileListsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list file lists params
func (o *ListFileListsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list file lists params
func (o *ListFileListsParams) WithHTTPClient(client *http.Client) *ListFileListsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list file lists params
func (o *ListFileListsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListFileListsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
