// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/jkawamoto/go-pixeldrain/pkg/pixeldrain/models"
)

// DeleteFileReader is a Reader for the DeleteFile structure.
type DeleteFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteFileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteFileOK creates a DeleteFileOK with default headers values
func NewDeleteFileOK() *DeleteFileOK {
	return &DeleteFileOK{}
}

/* DeleteFileOK describes a response with status code 200, with default header values.

OK
*/
type DeleteFileOK struct {
	Payload *DeleteFileOKBody
}

func (o *DeleteFileOK) Error() string {
	return fmt.Sprintf("[DELETE /file/{id}][%d] deleteFileOK  %+v", 200, o.Payload)
}
func (o *DeleteFileOK) GetPayload() *DeleteFileOKBody {
	return o.Payload
}

func (o *DeleteFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteFileOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFileDefault creates a DeleteFileDefault with default headers values
func NewDeleteFileDefault(code int) *DeleteFileDefault {
	return &DeleteFileDefault{
		_statusCode: code,
	}
}

/* DeleteFileDefault describes a response with status code -1, with default header values.

Error Response
*/
type DeleteFileDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the delete file default response
func (o *DeleteFileDefault) Code() int {
	return o._statusCode
}

func (o *DeleteFileDefault) Error() string {
	return fmt.Sprintf("[DELETE /file/{id}][%d] deleteFile default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteFileDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *DeleteFileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteFileOKBody delete file o k body
swagger:model DeleteFileOKBody
*/
type DeleteFileOKBody struct {

	// message
	// Example: The file has been deleted.
	Message string `json:"message,omitempty"`

	// success
	// Example: true
	Success bool `json:"success,omitempty"`

	// value
	// Example: file_deleted
	Value string `json:"value,omitempty"`
}

// Validate validates this delete file o k body
func (o *DeleteFileOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete file o k body based on context it is used
func (o *DeleteFileOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteFileOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteFileOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteFileOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
