// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-pixeldrain/pkg/pixeldrain/models"
)

// GetFileIDThumbnailReader is a Reader for the GetFileIDThumbnail structure.
type GetFileIDThumbnailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFileIDThumbnailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFileIDThumbnailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetFileIDThumbnailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetFileIDThumbnailOK creates a GetFileIDThumbnailOK with default headers values
func NewGetFileIDThumbnailOK() *GetFileIDThumbnailOK {
	return &GetFileIDThumbnailOK{}
}

/* GetFileIDThumbnailOK describes a response with status code 200, with default header values.

A PNG image of 100*100 px.
*/
type GetFileIDThumbnailOK struct {
}

func (o *GetFileIDThumbnailOK) Error() string {
	return fmt.Sprintf("[GET /file/{id}/thumbnail][%d] getFileIdThumbnailOK ", 200)
}

func (o *GetFileIDThumbnailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFileIDThumbnailDefault creates a GetFileIDThumbnailDefault with default headers values
func NewGetFileIDThumbnailDefault(code int) *GetFileIDThumbnailDefault {
	return &GetFileIDThumbnailDefault{
		_statusCode: code,
	}
}

/* GetFileIDThumbnailDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetFileIDThumbnailDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the get file ID thumbnail default response
func (o *GetFileIDThumbnailDefault) Code() int {
	return o._statusCode
}

func (o *GetFileIDThumbnailDefault) Error() string {
	return fmt.Sprintf("[GET /file/{id}/thumbnail][%d] GetFileIDThumbnail default  %+v", o._statusCode, o.Payload)
}
func (o *GetFileIDThumbnailDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetFileIDThumbnailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
