// Code generated by go-swagger; DO NOT EDIT.

package list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-pixeldrain/models"
)

// CreateFileListReader is a Reader for the CreateFileList structure.
type CreateFileListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFileListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateFileListCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 413:
		result := NewCreateFileListRequestEntityTooLarge()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewCreateFileListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateFileListCreated creates a CreateFileListCreated with default headers values
func NewCreateFileListCreated() *CreateFileListCreated {
	return &CreateFileListCreated{}
}

/*CreateFileListCreated handles this case with default header values.

List is created
*/
type CreateFileListCreated struct {
	Payload *CreateFileListCreatedBody
}

func (o *CreateFileListCreated) Error() string {
	return fmt.Sprintf("[POST /list][%d] createFileListCreated  %+v", 201, o.Payload)
}

func (o *CreateFileListCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateFileListCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFileListRequestEntityTooLarge creates a CreateFileListRequestEntityTooLarge with default headers values
func NewCreateFileListRequestEntityTooLarge() *CreateFileListRequestEntityTooLarge {
	return &CreateFileListRequestEntityTooLarge{}
}

/*CreateFileListRequestEntityTooLarge handles this case with default header values.

Payload too large
*/
type CreateFileListRequestEntityTooLarge struct {
	Payload *models.StandardError
}

func (o *CreateFileListRequestEntityTooLarge) Error() string {
	return fmt.Sprintf("[POST /list][%d] createFileListRequestEntityTooLarge  %+v", 413, o.Payload)
}

func (o *CreateFileListRequestEntityTooLarge) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFileListUnprocessableEntity creates a CreateFileListUnprocessableEntity with default headers values
func NewCreateFileListUnprocessableEntity() *CreateFileListUnprocessableEntity {
	return &CreateFileListUnprocessableEntity{}
}

/*CreateFileListUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type CreateFileListUnprocessableEntity struct {
	Payload *models.StandardError
}

func (o *CreateFileListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /list][%d] createFileListUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateFileListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateFileListBody create file list body
swagger:model CreateFileListBody
*/
type CreateFileListBody struct {

	// Description of the list.
	Description string `json:"description,omitempty"`

	// Ordered array of files to add to the list
	// Required: true
	Files []*FilesItems0 `json:"files"`

	// Title of the list.
	// Required: true
	Title *string `json:"title"`
}

// Validate validates this create file list body
func (o *CreateFileListBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateFiles(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateFileListBody) validateFiles(formats strfmt.Registry) error {

	if err := validate.Required("list"+"."+"files", "body", o.Files); err != nil {
		return err
	}

	for i := 0; i < len(o.Files); i++ {
		if swag.IsZero(o.Files[i]) { // not required
			continue
		}

		if o.Files[i] != nil {
			if err := o.Files[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("list" + "." + "files" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *CreateFileListBody) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("list"+"."+"title", "body", o.Title); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateFileListBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateFileListBody) UnmarshalBinary(b []byte) error {
	var res CreateFileListBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*CreateFileListCreatedBody create file list created body
swagger:model CreateFileListCreatedBody
*/
type CreateFileListCreatedBody struct {

	// ID of the newly created list
	ID string `json:"id,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this create file list created body
func (o *CreateFileListCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateFileListCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateFileListCreatedBody) UnmarshalBinary(b []byte) error {
	var res CreateFileListCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*FilesItems0 files items0
swagger:model FilesItems0
*/
type FilesItems0 struct {

	// Description of the file
	Description string `json:"description,omitempty"`

	// ID of the file
	ID string `json:"id,omitempty"`
}

// Validate validates this files items0
func (o *FilesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *FilesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *FilesItems0) UnmarshalBinary(b []byte) error {
	var res FilesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
