// Code generated by go-swagger; DO NOT EDIT.

package list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-pixeldrain/models"
)

// CreateFileListReader is a Reader for the CreateFileList structure.
type CreateFileListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFileListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateFileListCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateFileListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateFileListCreated creates a CreateFileListCreated with default headers values
func NewCreateFileListCreated() *CreateFileListCreated {
	return &CreateFileListCreated{}
}

/*
CreateFileListCreated describes a response with status code 201, with default header values.

List is created
*/
type CreateFileListCreated struct {
	Payload *models.SuccessResponse
}

// IsSuccess returns true when this create file list created response has a 2xx status code
func (o *CreateFileListCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create file list created response has a 3xx status code
func (o *CreateFileListCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create file list created response has a 4xx status code
func (o *CreateFileListCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create file list created response has a 5xx status code
func (o *CreateFileListCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create file list created response a status code equal to that given
func (o *CreateFileListCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create file list created response
func (o *CreateFileListCreated) Code() int {
	return 201
}

func (o *CreateFileListCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /list][%d] createFileListCreated %s", 201, payload)
}

func (o *CreateFileListCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /list][%d] createFileListCreated %s", 201, payload)
}

func (o *CreateFileListCreated) GetPayload() *models.SuccessResponse {
	return o.Payload
}

func (o *CreateFileListCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFileListDefault creates a CreateFileListDefault with default headers values
func NewCreateFileListDefault(code int) *CreateFileListDefault {
	return &CreateFileListDefault{
		_statusCode: code,
	}
}

/*
CreateFileListDefault describes a response with status code -1, with default header values.

Error Response
*/
type CreateFileListDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this create file list default response has a 2xx status code
func (o *CreateFileListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create file list default response has a 3xx status code
func (o *CreateFileListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create file list default response has a 4xx status code
func (o *CreateFileListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create file list default response has a 5xx status code
func (o *CreateFileListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create file list default response a status code equal to that given
func (o *CreateFileListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create file list default response
func (o *CreateFileListDefault) Code() int {
	return o._statusCode
}

func (o *CreateFileListDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /list][%d] createFileList default %s", o._statusCode, payload)
}

func (o *CreateFileListDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /list][%d] createFileList default %s", o._statusCode, payload)
}

func (o *CreateFileListDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *CreateFileListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
