// Code generated by go-swagger; DO NOT EDIT.

package list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetListIDParams creates a new GetListIDParams object
// with the default values initialized.
func NewGetListIDParams() *GetListIDParams {
	var ()
	return &GetListIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetListIDParamsWithTimeout creates a new GetListIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetListIDParamsWithTimeout(timeout time.Duration) *GetListIDParams {
	var ()
	return &GetListIDParams{

		timeout: timeout,
	}
}

// NewGetListIDParamsWithContext creates a new GetListIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetListIDParamsWithContext(ctx context.Context) *GetListIDParams {
	var ()
	return &GetListIDParams{

		Context: ctx,
	}
}

// NewGetListIDParamsWithHTTPClient creates a new GetListIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetListIDParamsWithHTTPClient(client *http.Client) *GetListIDParams {
	var ()
	return &GetListIDParams{
		HTTPClient: client,
	}
}

/*GetListIDParams contains all the parameters to send to the API endpoint
for the get list ID operation typically these are written to a http.Request
*/
type GetListIDParams struct {

	/*ID
	  ID of the list

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get list ID params
func (o *GetListIDParams) WithTimeout(timeout time.Duration) *GetListIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get list ID params
func (o *GetListIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get list ID params
func (o *GetListIDParams) WithContext(ctx context.Context) *GetListIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get list ID params
func (o *GetListIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get list ID params
func (o *GetListIDParams) WithHTTPClient(client *http.Client) *GetListIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get list ID params
func (o *GetListIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get list ID params
func (o *GetListIDParams) WithID(id string) *GetListIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get list ID params
func (o *GetListIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetListIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
