// Code generated by go-swagger; DO NOT EDIT.

package list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFileListParams creates a new GetFileListParams object
// with the default values initialized.
func NewGetFileListParams() *GetFileListParams {
	var ()
	return &GetFileListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFileListParamsWithTimeout creates a new GetFileListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFileListParamsWithTimeout(timeout time.Duration) *GetFileListParams {
	var ()
	return &GetFileListParams{

		timeout: timeout,
	}
}

// NewGetFileListParamsWithContext creates a new GetFileListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFileListParamsWithContext(ctx context.Context) *GetFileListParams {
	var ()
	return &GetFileListParams{

		Context: ctx,
	}
}

// NewGetFileListParamsWithHTTPClient creates a new GetFileListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFileListParamsWithHTTPClient(client *http.Client) *GetFileListParams {
	var ()
	return &GetFileListParams{
		HTTPClient: client,
	}
}

/*GetFileListParams contains all the parameters to send to the API endpoint
for the get file list operation typically these are written to a http.Request
*/
type GetFileListParams struct {

	/*ID
	  ID of the list

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get file list params
func (o *GetFileListParams) WithTimeout(timeout time.Duration) *GetFileListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get file list params
func (o *GetFileListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get file list params
func (o *GetFileListParams) WithContext(ctx context.Context) *GetFileListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get file list params
func (o *GetFileListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get file list params
func (o *GetFileListParams) WithHTTPClient(client *http.Client) *GetFileListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get file list params
func (o *GetFileListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get file list params
func (o *GetFileListParams) WithID(id string) *GetFileListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get file list params
func (o *GetFileListParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetFileListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
