// Code generated by go-swagger; DO NOT EDIT.

package list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-pixeldrain/models"
)

// GetFileListReader is a Reader for the GetFileList structure.
type GetFileListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFileListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFileListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetFileListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetFileListOK creates a GetFileListOK with default headers values
func NewGetFileListOK() *GetFileListOK {
	return &GetFileListOK{}
}

/*
GetFileListOK describes a response with status code 200, with default header values.

OK
*/
type GetFileListOK struct {
	Payload *models.GetFileListResponse
}

// IsSuccess returns true when this get file list o k response has a 2xx status code
func (o *GetFileListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get file list o k response has a 3xx status code
func (o *GetFileListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get file list o k response has a 4xx status code
func (o *GetFileListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get file list o k response has a 5xx status code
func (o *GetFileListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get file list o k response a status code equal to that given
func (o *GetFileListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get file list o k response
func (o *GetFileListOK) Code() int {
	return 200
}

func (o *GetFileListOK) Error() string {
	return fmt.Sprintf("[GET /list/{id}][%d] getFileListOK  %+v", 200, o.Payload)
}

func (o *GetFileListOK) String() string {
	return fmt.Sprintf("[GET /list/{id}][%d] getFileListOK  %+v", 200, o.Payload)
}

func (o *GetFileListOK) GetPayload() *models.GetFileListResponse {
	return o.Payload
}

func (o *GetFileListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetFileListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFileListDefault creates a GetFileListDefault with default headers values
func NewGetFileListDefault(code int) *GetFileListDefault {
	return &GetFileListDefault{
		_statusCode: code,
	}
}

/*
GetFileListDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetFileListDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this get file list default response has a 2xx status code
func (o *GetFileListDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get file list default response has a 3xx status code
func (o *GetFileListDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get file list default response has a 4xx status code
func (o *GetFileListDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get file list default response has a 5xx status code
func (o *GetFileListDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get file list default response a status code equal to that given
func (o *GetFileListDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get file list default response
func (o *GetFileListDefault) Code() int {
	return o._statusCode
}

func (o *GetFileListDefault) Error() string {
	return fmt.Sprintf("[GET /list/{id}][%d] getFileList default  %+v", o._statusCode, o.Payload)
}

func (o *GetFileListDefault) String() string {
	return fmt.Sprintf("[GET /list/{id}][%d] getFileList default  %+v", o._statusCode, o.Payload)
}

func (o *GetFileListDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetFileListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
