// Code generated by go-swagger; DO NOT EDIT.

package list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-pixeldrain/models"
)

// NewPostListParams creates a new PostListParams object
// with the default values initialized.
func NewPostListParams() *PostListParams {
	var ()
	return &PostListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostListParamsWithTimeout creates a new PostListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostListParamsWithTimeout(timeout time.Duration) *PostListParams {
	var ()
	return &PostListParams{

		timeout: timeout,
	}
}

// NewPostListParamsWithContext creates a new PostListParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostListParamsWithContext(ctx context.Context) *PostListParams {
	var ()
	return &PostListParams{

		Context: ctx,
	}
}

// NewPostListParamsWithHTTPClient creates a new PostListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostListParamsWithHTTPClient(client *http.Client) *PostListParams {
	var ()
	return &PostListParams{
		HTTPClient: client,
	}
}

/*PostListParams contains all the parameters to send to the API endpoint
for the post list operation typically these are written to a http.Request
*/
type PostListParams struct {

	/*List
	  POST body should be a JSON object, example below.  A list can contain maximally 5000 files. If you try to add more the request will fail.


	*/
	List *models.PostListParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post list params
func (o *PostListParams) WithTimeout(timeout time.Duration) *PostListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post list params
func (o *PostListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post list params
func (o *PostListParams) WithContext(ctx context.Context) *PostListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post list params
func (o *PostListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post list params
func (o *PostListParams) WithHTTPClient(client *http.Client) *PostListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post list params
func (o *PostListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithList adds the list to the post list params
func (o *PostListParams) WithList(list *models.PostListParamsBody) *PostListParams {
	o.SetList(list)
	return o
}

// SetList adds the list to the post list params
func (o *PostListParams) SetList(list *models.PostListParamsBody) {
	o.List = list
}

// WriteToRequest writes these params to a swagger request
func (o *PostListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.List != nil {
		if err := r.SetBodyParam(o.List); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
