// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFileIDParams creates a new DeleteFileIDParams object
// with the default values initialized.
func NewDeleteFileIDParams() *DeleteFileIDParams {
	var ()
	return &DeleteFileIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFileIDParamsWithTimeout creates a new DeleteFileIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFileIDParamsWithTimeout(timeout time.Duration) *DeleteFileIDParams {
	var ()
	return &DeleteFileIDParams{

		timeout: timeout,
	}
}

// NewDeleteFileIDParamsWithContext creates a new DeleteFileIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFileIDParamsWithContext(ctx context.Context) *DeleteFileIDParams {
	var ()
	return &DeleteFileIDParams{

		Context: ctx,
	}
}

// NewDeleteFileIDParamsWithHTTPClient creates a new DeleteFileIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFileIDParamsWithHTTPClient(client *http.Client) *DeleteFileIDParams {
	var ()
	return &DeleteFileIDParams{
		HTTPClient: client,
	}
}

/*DeleteFileIDParams contains all the parameters to send to the API endpoint
for the delete file ID operation typically these are written to a http.Request
*/
type DeleteFileIDParams struct {

	/*ID
	  ID of the file to request

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete file ID params
func (o *DeleteFileIDParams) WithTimeout(timeout time.Duration) *DeleteFileIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete file ID params
func (o *DeleteFileIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete file ID params
func (o *DeleteFileIDParams) WithContext(ctx context.Context) *DeleteFileIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete file ID params
func (o *DeleteFileIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete file ID params
func (o *DeleteFileIDParams) WithHTTPClient(client *http.Client) *DeleteFileIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete file ID params
func (o *DeleteFileIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete file ID params
func (o *DeleteFileIDParams) WithID(id string) *DeleteFileIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete file ID params
func (o *DeleteFileIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFileIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
