// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/jkawamoto/go-pixeldrain/models"
)

// DeleteFileReader is a Reader for the DeleteFile structure.
type DeleteFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteFileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteFileOK creates a DeleteFileOK with default headers values
func NewDeleteFileOK() *DeleteFileOK {
	return &DeleteFileOK{}
}

/*
DeleteFileOK describes a response with status code 200, with default header values.

OK
*/
type DeleteFileOK struct {
	Payload *DeleteFileOKBody
}

// IsSuccess returns true when this delete file o k response has a 2xx status code
func (o *DeleteFileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete file o k response has a 3xx status code
func (o *DeleteFileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete file o k response has a 4xx status code
func (o *DeleteFileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete file o k response has a 5xx status code
func (o *DeleteFileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete file o k response a status code equal to that given
func (o *DeleteFileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete file o k response
func (o *DeleteFileOK) Code() int {
	return 200
}

func (o *DeleteFileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /file/{id}][%d] deleteFileOK %s", 200, payload)
}

func (o *DeleteFileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /file/{id}][%d] deleteFileOK %s", 200, payload)
}

func (o *DeleteFileOK) GetPayload() *DeleteFileOKBody {
	return o.Payload
}

func (o *DeleteFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteFileOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteFileDefault creates a DeleteFileDefault with default headers values
func NewDeleteFileDefault(code int) *DeleteFileDefault {
	return &DeleteFileDefault{
		_statusCode: code,
	}
}

/*
DeleteFileDefault describes a response with status code -1, with default header values.

Error Response
*/
type DeleteFileDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this delete file default response has a 2xx status code
func (o *DeleteFileDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete file default response has a 3xx status code
func (o *DeleteFileDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete file default response has a 4xx status code
func (o *DeleteFileDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete file default response has a 5xx status code
func (o *DeleteFileDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete file default response a status code equal to that given
func (o *DeleteFileDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete file default response
func (o *DeleteFileDefault) Code() int {
	return o._statusCode
}

func (o *DeleteFileDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /file/{id}][%d] deleteFile default %s", o._statusCode, payload)
}

func (o *DeleteFileDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /file/{id}][%d] deleteFile default %s", o._statusCode, payload)
}

func (o *DeleteFileDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *DeleteFileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
DeleteFileOKBody delete file o k body
swagger:model DeleteFileOKBody
*/
type DeleteFileOKBody struct {

	// message
	// Example: The file has been deleted.
	Message string `json:"message,omitempty"`

	// success
	// Example: true
	Success bool `json:"success,omitempty"`

	// value
	// Example: file_deleted
	Value string `json:"value,omitempty"`
}

// Validate validates this delete file o k body
func (o *DeleteFileOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete file o k body based on context it is used
func (o *DeleteFileOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteFileOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteFileOKBody) UnmarshalBinary(b []byte) error {
	var res DeleteFileOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
