// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDownloadFileParams creates a new DownloadFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDownloadFileParams() *DownloadFileParams {
	return &DownloadFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadFileParamsWithTimeout creates a new DownloadFileParams object
// with the ability to set a timeout on a request.
func NewDownloadFileParamsWithTimeout(timeout time.Duration) *DownloadFileParams {
	return &DownloadFileParams{
		timeout: timeout,
	}
}

// NewDownloadFileParamsWithContext creates a new DownloadFileParams object
// with the ability to set a context for a request.
func NewDownloadFileParamsWithContext(ctx context.Context) *DownloadFileParams {
	return &DownloadFileParams{
		Context: ctx,
	}
}

// NewDownloadFileParamsWithHTTPClient creates a new DownloadFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewDownloadFileParamsWithHTTPClient(client *http.Client) *DownloadFileParams {
	return &DownloadFileParams{
		HTTPClient: client,
	}
}

/*
DownloadFileParams contains all the parameters to send to the API endpoint

	for the download file operation.

	Typically these are written to a http.Request.
*/
type DownloadFileParams struct {

	/* ID.

	   ID of the file to request
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the download file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadFileParams) WithDefaults() *DownloadFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the download file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the download file params
func (o *DownloadFileParams) WithTimeout(timeout time.Duration) *DownloadFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download file params
func (o *DownloadFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download file params
func (o *DownloadFileParams) WithContext(ctx context.Context) *DownloadFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download file params
func (o *DownloadFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download file params
func (o *DownloadFileParams) WithHTTPClient(client *http.Client) *DownloadFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download file params
func (o *DownloadFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the download file params
func (o *DownloadFileParams) WithID(id string) *DownloadFileParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the download file params
func (o *DownloadFileParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
