// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/jkawamoto/go-pixeldrain/models"
)

// DownloadFileReader is a Reader for the DownloadFile structure.
type DownloadFileReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *DownloadFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDownloadFileOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDownloadFileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDownloadFileOK creates a DownloadFileOK with default headers values
func NewDownloadFileOK(writer io.Writer) *DownloadFileOK {
	return &DownloadFileOK{
		Payload: writer,
	}
}

/*DownloadFileOK handles this case with default header values.

A file output stream.
*/
type DownloadFileOK struct {
	Payload io.Writer
}

func (o *DownloadFileOK) Error() string {
	return fmt.Sprintf("[GET /file/{id}][%d] downloadFileOK  %+v", 200, o.Payload)
}

func (o *DownloadFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDownloadFileDefault creates a DownloadFileDefault with default headers values
func NewDownloadFileDefault(code int) *DownloadFileDefault {
	return &DownloadFileDefault{
		_statusCode: code,
	}
}

/*DownloadFileDefault handles this case with default header values.

Error Response
*/
type DownloadFileDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the download file default response
func (o *DownloadFileDefault) Code() int {
	return o._statusCode
}

func (o *DownloadFileDefault) Error() string {
	return fmt.Sprintf("[GET /file/{id}][%d] downloadFile default  %+v", o._statusCode, o.Payload)
}

func (o *DownloadFileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
