// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-pixeldrain/models"
)

// DownloadFileReader is a Reader for the DownloadFile structure.
type DownloadFileReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *DownloadFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDownloadFileOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDownloadFileDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDownloadFileOK creates a DownloadFileOK with default headers values
func NewDownloadFileOK(writer io.Writer) *DownloadFileOK {
	return &DownloadFileOK{

		Payload: writer,
	}
}

/*
DownloadFileOK describes a response with status code 200, with default header values.

A file output stream.
*/
type DownloadFileOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this download file o k response has a 2xx status code
func (o *DownloadFileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this download file o k response has a 3xx status code
func (o *DownloadFileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this download file o k response has a 4xx status code
func (o *DownloadFileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this download file o k response has a 5xx status code
func (o *DownloadFileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this download file o k response a status code equal to that given
func (o *DownloadFileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the download file o k response
func (o *DownloadFileOK) Code() int {
	return 200
}

func (o *DownloadFileOK) Error() string {
	return fmt.Sprintf("[GET /file/{id}][%d] downloadFileOK  %+v", 200, o.Payload)
}

func (o *DownloadFileOK) String() string {
	return fmt.Sprintf("[GET /file/{id}][%d] downloadFileOK  %+v", 200, o.Payload)
}

func (o *DownloadFileOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *DownloadFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDownloadFileDefault creates a DownloadFileDefault with default headers values
func NewDownloadFileDefault(code int) *DownloadFileDefault {
	return &DownloadFileDefault{
		_statusCode: code,
	}
}

/*
DownloadFileDefault describes a response with status code -1, with default header values.

Error Response
*/
type DownloadFileDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this download file default response has a 2xx status code
func (o *DownloadFileDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this download file default response has a 3xx status code
func (o *DownloadFileDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this download file default response has a 4xx status code
func (o *DownloadFileDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this download file default response has a 5xx status code
func (o *DownloadFileDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this download file default response a status code equal to that given
func (o *DownloadFileDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the download file default response
func (o *DownloadFileDefault) Code() int {
	return o._statusCode
}

func (o *DownloadFileDefault) Error() string {
	return fmt.Sprintf("[GET /file/{id}][%d] downloadFile default  %+v", o._statusCode, o.Payload)
}

func (o *DownloadFileDefault) String() string {
	return fmt.Sprintf("[GET /file/{id}][%d] downloadFile default  %+v", o._statusCode, o.Payload)
}

func (o *DownloadFileDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *DownloadFileDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
