// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-pixeldrain/models"
)

// GetFileThumbnailReader is a Reader for the GetFileThumbnail structure.
type GetFileThumbnailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFileThumbnailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFileThumbnailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetFileThumbnailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetFileThumbnailOK creates a GetFileThumbnailOK with default headers values
func NewGetFileThumbnailOK() *GetFileThumbnailOK {
	return &GetFileThumbnailOK{}
}

/*
GetFileThumbnailOK describes a response with status code 200, with default header values.

A PNG image if a thumbnail can be generated. If a thumbnail cannot be generated you will get a 301 redirect to an image representing the type of the file.
*/
type GetFileThumbnailOK struct {
}

// IsSuccess returns true when this get file thumbnail o k response has a 2xx status code
func (o *GetFileThumbnailOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get file thumbnail o k response has a 3xx status code
func (o *GetFileThumbnailOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get file thumbnail o k response has a 4xx status code
func (o *GetFileThumbnailOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get file thumbnail o k response has a 5xx status code
func (o *GetFileThumbnailOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get file thumbnail o k response a status code equal to that given
func (o *GetFileThumbnailOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get file thumbnail o k response
func (o *GetFileThumbnailOK) Code() int {
	return 200
}

func (o *GetFileThumbnailOK) Error() string {
	return fmt.Sprintf("[GET /file/{id}/thumbnail][%d] getFileThumbnailOK", 200)
}

func (o *GetFileThumbnailOK) String() string {
	return fmt.Sprintf("[GET /file/{id}/thumbnail][%d] getFileThumbnailOK", 200)
}

func (o *GetFileThumbnailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFileThumbnailDefault creates a GetFileThumbnailDefault with default headers values
func NewGetFileThumbnailDefault(code int) *GetFileThumbnailDefault {
	return &GetFileThumbnailDefault{
		_statusCode: code,
	}
}

/*
GetFileThumbnailDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetFileThumbnailDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this get file thumbnail default response has a 2xx status code
func (o *GetFileThumbnailDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get file thumbnail default response has a 3xx status code
func (o *GetFileThumbnailDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get file thumbnail default response has a 4xx status code
func (o *GetFileThumbnailDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get file thumbnail default response has a 5xx status code
func (o *GetFileThumbnailDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get file thumbnail default response a status code equal to that given
func (o *GetFileThumbnailDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get file thumbnail default response
func (o *GetFileThumbnailDefault) Code() int {
	return o._statusCode
}

func (o *GetFileThumbnailDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /file/{id}/thumbnail][%d] getFileThumbnail default %s", o._statusCode, payload)
}

func (o *GetFileThumbnailDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /file/{id}/thumbnail][%d] getFileThumbnail default %s", o._statusCode, payload)
}

func (o *GetFileThumbnailDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetFileThumbnailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
