// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-pixeldrain/models"
)

// GetFileThumbnailReader is a Reader for the GetFileThumbnail structure.
type GetFileThumbnailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFileThumbnailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFileThumbnailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetFileThumbnailDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetFileThumbnailOK creates a GetFileThumbnailOK with default headers values
func NewGetFileThumbnailOK() *GetFileThumbnailOK {
	return &GetFileThumbnailOK{}
}

/* GetFileThumbnailOK describes a response with status code 200, with default header values.

A PNG image if a thumbnail can be generated. If a thumbnail cannot be generated you will get a 301 redirect to an image representing the type of the file.

*/
type GetFileThumbnailOK struct {
}

func (o *GetFileThumbnailOK) Error() string {
	return fmt.Sprintf("[GET /file/{id}/thumbnail][%d] getFileThumbnailOK ", 200)
}

func (o *GetFileThumbnailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFileThumbnailDefault creates a GetFileThumbnailDefault with default headers values
func NewGetFileThumbnailDefault(code int) *GetFileThumbnailDefault {
	return &GetFileThumbnailDefault{
		_statusCode: code,
	}
}

/* GetFileThumbnailDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetFileThumbnailDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// Code gets the status code for the get file thumbnail default response
func (o *GetFileThumbnailDefault) Code() int {
	return o._statusCode
}

func (o *GetFileThumbnailDefault) Error() string {
	return fmt.Sprintf("[GET /file/{id}/thumbnail][%d] getFileThumbnail default  %+v", o._statusCode, o.Payload)
}
func (o *GetFileThumbnailDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetFileThumbnailDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
