// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFileInfoParams creates a new GetFileInfoParams object
// with the default values initialized.
func NewGetFileInfoParams() *GetFileInfoParams {
	var ()
	return &GetFileInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFileInfoParamsWithTimeout creates a new GetFileInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFileInfoParamsWithTimeout(timeout time.Duration) *GetFileInfoParams {
	var ()
	return &GetFileInfoParams{

		timeout: timeout,
	}
}

// NewGetFileInfoParamsWithContext creates a new GetFileInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFileInfoParamsWithContext(ctx context.Context) *GetFileInfoParams {
	var ()
	return &GetFileInfoParams{

		Context: ctx,
	}
}

// NewGetFileInfoParamsWithHTTPClient creates a new GetFileInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFileInfoParamsWithHTTPClient(client *http.Client) *GetFileInfoParams {
	var ()
	return &GetFileInfoParams{
		HTTPClient: client,
	}
}

/*GetFileInfoParams contains all the parameters to send to the API endpoint
for the get file info operation typically these are written to a http.Request
*/
type GetFileInfoParams struct {

	/*ID
	  ID(s) of the file

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get file info params
func (o *GetFileInfoParams) WithTimeout(timeout time.Duration) *GetFileInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get file info params
func (o *GetFileInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get file info params
func (o *GetFileInfoParams) WithContext(ctx context.Context) *GetFileInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get file info params
func (o *GetFileInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get file info params
func (o *GetFileInfoParams) WithHTTPClient(client *http.Client) *GetFileInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get file info params
func (o *GetFileInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get file info params
func (o *GetFileInfoParams) WithID(id string) *GetFileInfoParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get file info params
func (o *GetFileInfoParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetFileInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
