// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jkawamoto/go-pixeldrain/models"
)

// GetFileInfoReader is a Reader for the GetFileInfo structure.
type GetFileInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFileInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFileInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetFileInfoDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetFileInfoOK creates a GetFileInfoOK with default headers values
func NewGetFileInfoOK() *GetFileInfoOK {
	return &GetFileInfoOK{}
}

/*
GetFileInfoOK describes a response with status code 200, with default header values.

OK
*/
type GetFileInfoOK struct {
	Payload *models.FileInfo
}

// IsSuccess returns true when this get file info o k response has a 2xx status code
func (o *GetFileInfoOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get file info o k response has a 3xx status code
func (o *GetFileInfoOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get file info o k response has a 4xx status code
func (o *GetFileInfoOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get file info o k response has a 5xx status code
func (o *GetFileInfoOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get file info o k response a status code equal to that given
func (o *GetFileInfoOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get file info o k response
func (o *GetFileInfoOK) Code() int {
	return 200
}

func (o *GetFileInfoOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /file/{id}/info][%d] getFileInfoOK %s", 200, payload)
}

func (o *GetFileInfoOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /file/{id}/info][%d] getFileInfoOK %s", 200, payload)
}

func (o *GetFileInfoOK) GetPayload() *models.FileInfo {
	return o.Payload
}

func (o *GetFileInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FileInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFileInfoDefault creates a GetFileInfoDefault with default headers values
func NewGetFileInfoDefault(code int) *GetFileInfoDefault {
	return &GetFileInfoDefault{
		_statusCode: code,
	}
}

/*
GetFileInfoDefault describes a response with status code -1, with default header values.

Error Response
*/
type GetFileInfoDefault struct {
	_statusCode int

	Payload *models.StandardError
}

// IsSuccess returns true when this get file info default response has a 2xx status code
func (o *GetFileInfoDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get file info default response has a 3xx status code
func (o *GetFileInfoDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get file info default response has a 4xx status code
func (o *GetFileInfoDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get file info default response has a 5xx status code
func (o *GetFileInfoDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get file info default response a status code equal to that given
func (o *GetFileInfoDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get file info default response
func (o *GetFileInfoDefault) Code() int {
	return o._statusCode
}

func (o *GetFileInfoDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /file/{id}/info][%d] getFileInfo default %s", o._statusCode, payload)
}

func (o *GetFileInfoDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /file/{id}/info][%d] getFileInfo default %s", o._statusCode, payload)
}

func (o *GetFileInfoDefault) GetPayload() *models.StandardError {
	return o.Payload
}

func (o *GetFileInfoDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
