// Code generated by go-swagger; DO NOT EDIT.

package file

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"os"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostFileParams creates a new PostFileParams object
// with the default values initialized.
func NewPostFileParams() *PostFileParams {
	var (
		descriptionDefault = string("Pixeldrain File")
		nameDefault        = string("Name of file param")
	)
	return &PostFileParams{
		Description: &descriptionDefault,
		Name:        &nameDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFileParamsWithTimeout creates a new PostFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFileParamsWithTimeout(timeout time.Duration) *PostFileParams {
	var (
		descriptionDefault = string("Pixeldrain File")
		nameDefault        = string("Name of file param")
	)
	return &PostFileParams{
		Description: &descriptionDefault,
		Name:        &nameDefault,

		timeout: timeout,
	}
}

// NewPostFileParamsWithContext creates a new PostFileParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFileParamsWithContext(ctx context.Context) *PostFileParams {
	var (
		descriptionDefault = string("Pixeldrain File")
		nameDefault        = string("Name of file param")
	)
	return &PostFileParams{
		Description: &descriptionDefault,
		Name:        &nameDefault,

		Context: ctx,
	}
}

// NewPostFileParamsWithHTTPClient creates a new PostFileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFileParamsWithHTTPClient(client *http.Client) *PostFileParams {
	var (
		descriptionDefault = string("Pixeldrain File")
		nameDefault        = string("Name of file param")
	)
	return &PostFileParams{
		Description: &descriptionDefault,
		Name:        &nameDefault,
		HTTPClient:  client,
	}
}

/*PostFileParams contains all the parameters to send to the API endpoint
for the post file operation typically these are written to a http.Request
*/
type PostFileParams struct {

	/*Description
	  Description of the file

	*/
	Description *string
	/*File
	  Multipart file to upload

	*/
	File os.File
	/*Name
	  Name of the file to upload

	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post file params
func (o *PostFileParams) WithTimeout(timeout time.Duration) *PostFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post file params
func (o *PostFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post file params
func (o *PostFileParams) WithContext(ctx context.Context) *PostFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post file params
func (o *PostFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post file params
func (o *PostFileParams) WithHTTPClient(client *http.Client) *PostFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post file params
func (o *PostFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the post file params
func (o *PostFileParams) WithDescription(description *string) *PostFileParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the post file params
func (o *PostFileParams) SetDescription(description *string) {
	o.Description = description
}

// WithFile adds the file to the post file params
func (o *PostFileParams) WithFile(file os.File) *PostFileParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the post file params
func (o *PostFileParams) SetFile(file os.File) {
	o.File = file
}

// WithName adds the name to the post file params
func (o *PostFileParams) WithName(name *string) *PostFileParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post file params
func (o *PostFileParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PostFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Description != nil {

		// form param description
		var frDescription string
		if o.Description != nil {
			frDescription = *o.Description
		}
		fDescription := frDescription
		if fDescription != "" {
			if err := r.SetFormParam("description", fDescription); err != nil {
				return err
			}
		}

	}

	// form file param file
	if err := r.SetFileParam("file", &o.File); err != nil {
		return err
	}

	if o.Name != nil {

		// form param name
		var frName string
		if o.Name != nil {
			frName = *o.Name
		}
		fName := frName
		if fName != "" {
			if err := r.SetFormParam("name", fName); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
