// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
)

// GetFileIDOKBody get file Id o k body
// swagger:model getFileIdOKBody
type GetFileIDOKBody *runtime.File

//// Validate validates this get file Id o k body
//func (m GetFileIDOKBody) Validate(formats strfmt.Registry) error {
//	return nil
//}
