// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetListIDOKBodyFilesItems get list Id o k body files items
// swagger:model getListIdOKBodyFilesItems
type GetListIDOKBodyFilesItems struct {

	// date created
	DateCreated float64 `json:"date_created,omitempty"`

	// date last view
	DateLastView float64 `json:"date_last_view,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// detail href
	DetailHref string `json:"detail_href,omitempty"`

	// file name
	FileName string `json:"file_name,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// list description
	ListDescription string `json:"list_description,omitempty"`
}

// Validate validates this get list Id o k body files items
func (m *GetListIDOKBodyFilesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetListIDOKBodyFilesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetListIDOKBodyFilesItems) UnmarshalBinary(b []byte) error {
	var res GetListIDOKBodyFilesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
