// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostListParamsBodyFilesItems post list params body files items
// swagger:model postListParamsBodyFilesItems
type PostListParamsBodyFilesItems struct {

	// Description of the file
	Description string `json:"description,omitempty"`

	// ID of the file
	ID string `json:"id,omitempty"`
}

// Validate validates this post list params body files items
func (m *PostListParamsBodyFilesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostListParamsBodyFilesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostListParamsBodyFilesItems) UnmarshalBinary(b []byte) error {
	var res PostListParamsBodyFilesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
