// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostListOKBody post list o k body
// swagger:model postListOKBody
type PostListOKBody struct {

	// ID of the newly created list
	ID string `json:"id,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this post list o k body
func (m *PostListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostListOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostListOKBody) UnmarshalBinary(b []byte) error {
	var res PostListOKBody
	fmt.Println(string(b))
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
